tags:
- Package -> task
parameters:
  - in: body
    name: sendResetLinkRequest
    type: Object
    schema:
      $ref: "#/definitions/DeleteTask"
    
responses:
  "200":
    description: ""
    content:
      application/json:
        schema:
          type: "string"
  "404":
    description: ""

definitions:
  DeleteTask:
    type: object
    properties:
      taskId:
        type: string
        example: "1"




